spring:
  datasource:
    username: root
    password: root
    # 我是用的 mysql 8版本 向下支持 mysql 5 所以如果是 mysql 5 也可以使用一样的 url \ driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      # 删除用 1
      logic-delete-field: 1
      # 未删除用 0
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
